"""Pathology / WSI HTTP surface.

Read + deep-zoom serving for whole-slide images and ordinary pathology
images (gross specimen photos, static micrographs), all gated on the same
visibility OR as imaging studies (own / OpenData / public).

Tiles are PRE-GENERATED by the ``tile_wsi`` worker into the derivatives
bucket (a DeepZoom pyramid) and served here as a stateless S3 proxy — no
per-request OpenSlide/pyvips work, no source file on the API pod. This
deep-zoom path was chosen over on-the-fly tiling because the production
pods are ephemeral and disk-constrained: caching multi-GB source slides
locally to tile them on demand risks node DiskPressure (see
``docs/pathology_wsi_spike.md`` Step 2 + the plan decision).

Storage isolation per memory ``feedback-storage-isolation``: clients
never see S3 keys or bucket names. Tiles + descriptors stream through
this API from the derivatives bucket; the source slide is never exposed.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, Query, Response
from fastapi.concurrency import run_in_threadpool
from pydantic import BaseModel, ConfigDict
from sqlalchemy import ColumnElement, or_, select, true
from sqlalchemy.ext.asyncio import AsyncSession

from bvphoenix.auth import optional_user
from bvphoenix.config import get_settings
from bvphoenix.db.models import PathologySlide, User
from bvphoenix.db.session import get_db
from bvphoenix.services.pathology_keys import dzi_tile_key
from bvphoenix.services.permissions import platform_owner_subject_id
from bvphoenix.storage import get_s3_storage

router = APIRouter(tags=["pathology"])

# Region-extraction guardrails (the /region endpoint is the MCP / agent
# "look at the slide" surface, so it must be cheap + DoS-resistant).
_REGION_MAX_PIXELS = 16 * 1024 * 1024  # 16 MP output cap
_REGION_MAX_TILES = 64  # at most this many tile GETs per call


class PathologySlideOut(BaseModel):
    """Public projection of ``pathology_slides``.

    Mirrors the StudyOut shape: license / provenance / is_opendata
    bubble up so the frontend can render the same chips it already
    uses on imaging study cards.
    """

    model_config = ConfigDict(from_attributes=True)

    id: uuid.UUID
    patient_id: uuid.UUID
    clinical_event_id: uuid.UUID | None = None
    slide_instance_uid: str
    block_label: str | None = None
    slide_label: str | None = None
    stain: str | None = None
    scanner_make: str | None = None
    scanner_model: str | None = None
    magnification: float | None = None
    mpp_x: float | None = None
    mpp_y: float | None = None
    base_width: int | None = None
    base_height: int | None = None
    pyramid_levels: int | None = None
    source_format: str
    slide_class: str = "wsi"
    contribution_tier: str
    is_public: bool
    ingestion_complete: bool
    label_redacted: bool
    has_macro: bool = False
    # Deep-zoom tiling state (Step 2 viewer).
    dzi_ready: bool = False
    has_dzi: bool = False
    dzi_tile_size: int | None = None
    dzi_levels: int | None = None
    dzi_format: str | None = None
    source_collection: str | None = None
    license_spdx: str | None = None
    license_url: str | None = None
    citation_required: bool = False
    citation_text: str | None = None
    # See StudyOut.commercial_use_allowed — False when license_spdx carries
    # a NonCommercial (-NC) clause.
    commercial_use_allowed: bool = True
    is_opendata: bool = False
    created_at: datetime

    @classmethod
    def model_validate(cls, obj, *args, **kwargs):  # type: ignore[override]
        from bvphoenix.services.licensing import license_allows_commercial_use

        out = super().model_validate(obj, *args, **kwargs)
        owner = getattr(obj, "owner_subject_id", None)
        if owner is not None:
            try:
                out.is_opendata = owner == platform_owner_subject_id()
            except Exception:
                out.is_opendata = False
        out.has_macro = getattr(obj, "s3_macro_key", None) is not None
        out.has_dzi = bool(getattr(obj, "dzi_ready", False))
        out.commercial_use_allowed = license_allows_commercial_use(out.license_spdx)
        return out


def _visible_slides_where(user: User | None) -> ColumnElement[bool]:
    """SQL predicate for the slides a caller may see. Single source of
    truth shared by the list query and the single-slide loader so they
    cannot drift (a drift here is a PHI-leak vector). Anonymous → public
    only; admin → all; otherwise public OR OpenData OR own."""
    if user is None:
        return PathologySlide.is_public.is_(True)
    if getattr(user, "is_admin", False):
        return true()
    return or_(
        PathologySlide.is_public.is_(True),
        PathologySlide.owner_subject_id == platform_owner_subject_id(),
        PathologySlide.owner_subject_id == user.subject_id,
    )


async def _load_visible_slide(
    db: AsyncSession, *, slide_id: uuid.UUID, user: User | None
) -> PathologySlide:
    """Fetch a slide subject to the shared visibility predicate. Returns
    404 both for a missing row and a hidden one (no existence leak)."""
    row = (
        await db.execute(
            select(PathologySlide).where(PathologySlide.id == slide_id, _visible_slides_where(user))
        )
    ).scalar_one_or_none()
    if row is None:
        raise HTTPException(status_code=404, detail="slide not found")
    return row


@router.get("/pathology-slides", response_model=list[PathologySlideOut])
async def list_pathology_slides(
    db: Annotated[AsyncSession, Depends(get_db)],
    user: Annotated[User | None, Depends(optional_user)],
    patient_id: uuid.UUID | None = None,
    public_only: bool = True,
    limit: Annotated[int, Query(ge=1, le=200)] = 60,
    offset: Annotated[int, Query(ge=0)] = 0,
) -> list[PathologySlideOut]:
    """List ingested slides, newest first.

    ``public_only`` (the default) drives the OpenData public-pathology
    library grid. ``patient_id`` narrows to one patient's slides for the
    clinical viewer's slide tray; the visibility predicate still
    authorises (the filter narrows, it never widens). Slides still tiling
    (``dzi_ready=false``) ARE returned so the UI can show a processing
    state.
    """
    stmt = select(PathologySlide).where(PathologySlide.ingestion_complete.is_(True))
    if public_only or user is None:
        # Anonymous callers are always restricted to public regardless of
        # the flag.
        stmt = stmt.where(PathologySlide.is_public.is_(True))
    else:
        stmt = stmt.where(_visible_slides_where(user))
    if patient_id is not None:
        stmt = stmt.where(PathologySlide.patient_id == patient_id)
    stmt = stmt.order_by(PathologySlide.created_at.desc()).limit(limit).offset(offset)
    rows = (await db.execute(stmt)).scalars().all()
    return [PathologySlideOut.model_validate(r) for r in rows]


@router.get("/pathology-slides/{slide_id}", response_model=PathologySlideOut)
async def get_pathology_slide(
    slide_id: uuid.UUID,
    db: Annotated[AsyncSession, Depends(get_db)],
    user: Annotated[User | None, Depends(optional_user)],
) -> PathologySlideOut:
    slide = await _load_visible_slide(db, slide_id=slide_id, user=user)
    return PathologySlideOut.model_validate(slide)


def _tile_cache_control(is_public: bool) -> str:
    """Tiles are content-immutable (keyed by slide+level+col+row) and
    de-identified (tissue pyramid, no label). ``public`` lets a CDN /
    shared cache hold public-slide tiles — essential because OSD fetches
    hundreds per pan. Private slides MUST stay ``private`` so a shared
    cache can't leak tissue tiles across users (a real PHI control)."""
    scope = "public" if is_public else "private"
    return f"{scope}, max-age=31536000, immutable"


@router.get("/pathology-slides/{slide_id}/dzi")
async def get_pathology_slide_dzi(
    slide_id: uuid.UUID,
    db: Annotated[AsyncSession, Depends(get_db)],
    user: Annotated[User | None, Depends(optional_user)],
) -> Response:
    """DeepZoom ``.dzi`` XML descriptor for the OpenSeadragon viewer.

    Hybrid serving:

    * If the ``tile_wsi`` worker pre-generated the pyramid (``dzi_ready``),
      stream the descriptor from the derivatives bucket — cheap, cached,
      the default for ordinary-size slides.
    * Otherwise fall back to ON-THE-FLY tiling (``services.wsi_tiles``):
      gigapixel slides (CAMELYON, ~150k tiles) exceed the worker's 30-min
      job timeout and would never pre-generate, so they are tiled live from
      a bounded S3-source cache rather than 409-ing forever.
    """
    slide = await _load_visible_slide(db, slide_id=slide_id, user=user)
    if slide.dzi_ready and slide.s3_dzi_key:
        storage = get_s3_storage()
        derivatives = get_settings().s3_bucket_derivatives
        body = await run_in_threadpool(
            storage.get_object_bytes, bucket=derivatives, key=slide.s3_dzi_key
        )
        return Response(
            content=body,
            media_type="application/xml",
            headers={"Cache-Control": _tile_cache_control(slide.is_public)},
        )
    if not slide.s3_source_key:
        raise HTTPException(status_code=409, detail="tiles not ready")
    from bvphoenix.services.wsi_tiles import get_dzi_xml

    xml = await run_in_threadpool(get_dzi_xml, slide)
    return Response(
        content=xml,
        media_type="application/xml",
        headers={"Cache-Control": _tile_cache_control(slide.is_public)},
    )


@router.get("/pathology-slides/{slide_id}/tiles/{level}/{col}/{row}")
async def get_pathology_slide_tile(
    slide_id: uuid.UUID,
    level: int,
    col: int,
    row: int,
    db: Annotated[AsyncSession, Depends(get_db)],
    user: Annotated[User | None, Depends(optional_user)],
) -> Response:
    """One DeepZoom JPEG tile. Hybrid: pre-generated tile from the
    derivatives bucket when ``dzi_ready``, else tiled on the fly from the
    source (gigapixel slides that never pre-generate). Visibility-gated,
    storage-isolated either way."""
    slide = await _load_visible_slide(db, slide_id=slide_id, user=user)
    if level < 0 or col < 0 or row < 0:
        raise HTTPException(status_code=404, detail="tile out of range")
    if slide.dzi_ready:
        if slide.dzi_levels is not None and level >= slide.dzi_levels:
            raise HTTPException(status_code=404, detail="tile out of range")
        storage = get_s3_storage()
        derivatives = get_settings().s3_bucket_derivatives
        key = dzi_tile_key(slide_id, level, col, row, fmt="jpg")
        try:
            body = await run_in_threadpool(storage.get_object_bytes, bucket=derivatives, key=key)
        except Exception as exc:  # NoSuchKey for an out-of-grid address
            raise HTTPException(status_code=404, detail="tile out of range") from exc
        return Response(
            content=body,
            media_type="image/jpeg",
            headers={"Cache-Control": _tile_cache_control(slide.is_public)},
        )
    if not slide.s3_source_key:
        raise HTTPException(status_code=409, detail="tiles not ready")
    from bvphoenix.services.wsi_tiles import get_tile_jpeg

    try:
        body = await run_in_threadpool(get_tile_jpeg, slide, level=level, col=col, row=row)
    except KeyError as exc:
        raise HTTPException(status_code=404, detail="tile out of range") from exc
    return Response(
        content=body,
        media_type="image/jpeg",
        headers={"Cache-Control": _tile_cache_control(slide.is_public)},
    )


def _stitch_region(
    *,
    derivatives_bucket: str,
    slide_id: uuid.UUID,
    level: int,
    x: int,
    y: int,
    w: int,
    h: int,
    tile_size: int,
) -> bytes:
    """Compose a (w×h) RGB JPEG from the stored DZI tiles covering the
    requested rect at ``level``. Stateless — reads only derivatives-bucket
    tiles, never the source (the backend has no libopenslide and the
    source is not on the pod). overlap=0 makes tile seams clean."""
    from io import BytesIO

    from PIL import Image

    storage = get_s3_storage()
    canvas = Image.new("RGB", (w, h))
    col0, col1 = x // tile_size, (x + w - 1) // tile_size
    row0, row1 = y // tile_size, (y + h - 1) // tile_size
    for c in range(col0, col1 + 1):
        for r in range(row0, row1 + 1):
            key = dzi_tile_key(slide_id, level, c, r, fmt="jpg")
            try:
                tb = storage.get_object_bytes(bucket=derivatives_bucket, key=key)
            except Exception:
                continue  # missing edge tile: leave that area black
            with Image.open(BytesIO(tb)) as tile:
                rgb = tile.convert("RGB")
                canvas.paste(rgb, (c * tile_size - x, r * tile_size - y))
    out = BytesIO()
    canvas.save(out, format="JPEG", quality=85)
    return out.getvalue()


@router.get("/pathology-slides/{slide_id}/region")
async def get_pathology_slide_region(
    slide_id: uuid.UUID,
    db: Annotated[AsyncSession, Depends(get_db)],
    user: Annotated[User | None, Depends(optional_user)],
    x: Annotated[int, Query(ge=0)],
    y: Annotated[int, Query(ge=0)],
    w: Annotated[int, Query(ge=1)],
    h: Annotated[int, Query(ge=1)],
    level: Annotated[int, Query(ge=0)],
) -> Response:
    """Stitch a (w×h) JPEG region at a DZI ``level`` from stored tiles.

    The MCP "look at the slide" + report-ROI-snapshot surface. Bounded to
    16 MP / ~64 tiles per call so it stays cheap and DoS-resistant.
    """
    slide = await _load_visible_slide(db, slide_id=slide_id, user=user)
    if not slide.dzi_ready:
        raise HTTPException(status_code=409, detail="tiles not ready")
    if slide.dzi_levels is not None and level >= slide.dzi_levels:
        raise HTTPException(status_code=404, detail="level out of range")
    if w * h > _REGION_MAX_PIXELS:
        raise HTTPException(status_code=413, detail="region too large (max 16 MP)")
    tile_size = slide.dzi_tile_size or 512
    n_tiles = ((x + w - 1) // tile_size - x // tile_size + 1) * (
        (y + h - 1) // tile_size - y // tile_size + 1
    )
    if n_tiles > _REGION_MAX_TILES:
        raise HTTPException(status_code=413, detail="region spans too many tiles")
    derivatives = get_settings().s3_bucket_derivatives
    body = await run_in_threadpool(
        _stitch_region,
        derivatives_bucket=derivatives,
        slide_id=slide_id,
        level=level,
        x=x,
        y=y,
        w=w,
        h=h,
        tile_size=tile_size,
    )
    return Response(
        content=body,
        media_type="image/jpeg",
        headers={"Cache-Control": _tile_cache_control(slide.is_public)},
    )


@router.get("/pathology-slides/{slide_id}/thumbnail")
async def get_pathology_slide_thumbnail(
    slide_id: uuid.UUID,
    db: Annotated[AsyncSession, Depends(get_db)],
    user: Annotated[User | None, Depends(optional_user)],
) -> Response:
    """Stream the pre-generated thumbnail JPEG.

    The bytes were rendered at ingest time (see
    ``services.wsi_deid.generate_thumbnail_jpeg`` / the ordinary-image
    Pillow path) so this endpoint is a thin S3 GET. Returns 404 when the
    slide exists but the ingestion did not produce a thumbnail.
    """
    slide = await _load_visible_slide(db, slide_id=slide_id, user=user)
    if not slide.s3_thumbnail_key:
        raise HTTPException(status_code=404, detail="thumbnail not generated")
    storage = get_s3_storage()
    body = storage.get_object_bytes(bucket=slide.s3_bucket, key=slide.s3_thumbnail_key)
    return Response(
        content=body,
        media_type="image/jpeg",
        # 1 day immutable cache: thumbnails are content-addressed via
        # slide_id, never regenerated in place.
        headers={"Cache-Control": "private, max-age=86400, immutable"},
    )


@router.get("/pathology-slides/{slide_id}/macro")
async def get_pathology_slide_macro(
    slide_id: uuid.UUID,
    db: Annotated[AsyncSession, Depends(get_db)],
    user: Annotated[User | None, Depends(optional_user)],
) -> Response:
    """Stream the macro overview JPEG, if the scanner embedded one."""
    slide = await _load_visible_slide(db, slide_id=slide_id, user=user)
    if not slide.s3_macro_key:
        raise HTTPException(status_code=404, detail="no macro image for this slide")
    storage = get_s3_storage()
    body = storage.get_object_bytes(bucket=slide.s3_bucket, key=slide.s3_macro_key)
    return Response(
        content=body,
        media_type="image/jpeg",
        headers={"Cache-Control": "private, max-age=86400, immutable"},
    )
