"use client";

// "Invia studio a un collega" — purpose-specific share UI.
//
// Sits on top of the existing share-link primitives but is opinionated
// for the consult workflow: defaults to pseudonymized DICOMs, defaults
// to autogenerated password (delivered out-of-band), pulls recipient
// candidates from the patient's contact list, and offers two delivery
// modes (email from bitvision, copy link). The generic ShareDialog
// stays for "give a colleague editor access on the fascicolo"; this
// dialog is for "consegna lo studio al primario per il consulto".
//
// Why a separate component: the affordances we want to *expose* are
// different (deidentify front and centre, recipient-from-contacts
// autocomplete, two-mode delivery toggle), and the affordances we
// want to *hide* are different too (no anonymous mode, no editor
// access, no per-action permission picker). Bolting these onto
// ShareDialog would have produced a 700-line component with two
// disjoint flows interleaved.

import { useLocale, useTranslations } from "next-intl";
import Link from "next/link";
import QRCode from "qrcode";
import { useEffect, useMemo, useState } from "react";
import { createPortal } from "react-dom";

import {
  ApiError,
  type PatientContact,
  type ShareLink,
  foldersApi,
  patientsApi,
  studiesApi,
} from "@/lib/api";

interface Props {
  /** Target resource kind. ``"study"`` (default) creates a study
   *  share via ``POST /studies/{id}/share``; ``"folder"`` creates a
   *  folder share via ``POST /folders/{id}/share-link``;
   *  ``"patient"`` creates a fascicolo share via
   *  ``POST /patients/{id}/share``. The dialog surface is the same
   *  across kinds; only the API call branches and the
   *  patient-specific affordances (AI sponsorship cap) appear when
   *  ``kind === "patient"``. */
  kind?: "study" | "folder" | "patient";
  /** ID of the target resource. ``studyId`` for studies,
   *  ``folderId`` for folders, ``patientId`` for fascicolo shares
   *  (same field, kind disambiguates). */
  studyId: string;
  /** The patient that owns the resource. Used to pull contacts for
   *  the autocomplete and label the patient on the email. For
   *  ``kind="patient"`` shares, ``studyId`` and ``patientId`` are
   *  the same — pass both for clarity. */
  patientId: string;
  /** Friendly label (study description / folder name / patient
   *  display name) used as a hint inside the prefilled mailto:
   *  subject when the user picks "copy link" delivery. */
  studyLabel?: string | null;
  open: boolean;
  onClose: () => void;
}

type ExpiryChoice = "week" | "month1" | "month3" | "month6" | "year";

// Hours-per-choice. Calendar months are approximated as 30 days
// (matches the backend extend semantics, see
// ``share_links/{id}/extend``). The UI label says "circa N mesi"
// so the user expects the heuristic.
const EXPIRY_HOURS: Record<ExpiryChoice, number> = {
  week: 24 * 7,
  month1: 24 * 30,
  month3: 24 * 90,
  month6: 24 * 180,
  year: 24 * 365,
};

type DeliveryMode = "email" | "copy";

/**
 * Filter the patient's contacts down to those that could plausibly
 * receive an email. Contacts without ``email`` (phone-only, e.g. an
 * elderly family member's WhatsApp number) wouldn't be useful here.
 */
function contactsWithEmail(contacts: PatientContact[]): PatientContact[] {
  return contacts.filter((c) => !!c.email && c.email.trim().length > 0);
}

export default function SendStudyDialog({
  kind = "study",
  studyId,
  patientId,
  studyLabel,
  open,
  onClose,
}: Props) {
  const t = useTranslations("sendStudy");
  const locale = useLocale();

  const [contacts, setContacts] = useState<PatientContact[]>([]);
  const [recipientFromList, setRecipientFromList] = useState<string>("");
  const [freeName, setFreeName] = useState("");
  const [freeEmail, setFreeEmail] = useState("");
  const [useFreeForm, setUseFreeForm] = useState(false);

  const [deidentify, setDeidentify] = useState(true);
  const [expiry, setExpiry] = useState<ExpiryChoice>("month1");
  const [autogenPassword, setAutogenPassword] = useState(true);
  const [deliveryMode, setDeliveryMode] = useState<DeliveryMode>("email");
  const [customMessage, setCustomMessage] = useState("");
  // Optional human-readable label so the grantor can tell apart
  // multiple shares of the same study to different colleagues
  // ("Consulto Bianchi 2026-05", "Per radiologia interna", ...).
  // Persisted on ShareLink.label and surfaced in the management
  // table.
  const [label, setLabel] = useState("");
  // AI sponsorship (patient-scoped shares only). When toggled on,
  // claiming the link auto-creates a WalletSponsorship of the share
  // creator's wallet up to ``aiCapEur`` so the recipient can run AI
  // on the shared record at the creator's expense. OFF by default so
  // legacy "recipient pays" remains the safe default.
  const [aiSponsor, setAiSponsor] = useState(false);
  const [aiCapEur, setAiCapEur] = useState<string>("5.00");

  const [busy, setBusy] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [generatedPassword, setGeneratedPassword] = useState<string | null>(null);
  const [success, setSuccess] = useState<string | null>(null);
  // Holds the ShareLink record after a successful create so the
  // post-submit view can offer "Copia di nuovo" + "Apri client mail"
  // without re-triggering the create flow. Set in handleSubmit.
  const [createdLink, setCreatedLink] = useState<ShareLink | null>(null);
  const [copyFlash, setCopyFlash] = useState<"copied" | "failed" | null>(null);
  const [showQr, setShowQr] = useState(false);
  const [qrDataUrl, setQrDataUrl] = useState<string | null>(null);
  const [qrError, setQrError] = useState(false);

  // Pull contacts on open. Failures are non-fatal (the user can still
  // type a free-form recipient).
  useEffect(() => {
    if (!open) return;
    let cancelled = false;
    void (async () => {
      try {
        const patient = await patientsApi.detail(patientId);
        if (cancelled) return;
        const eligible = contactsWithEmail(patient.contacts || []);
        setContacts(eligible);
        if (eligible.length > 0) {
          setRecipientFromList(eligible[0].id || eligible[0].email || "");
          setUseFreeForm(false);
        } else {
          setUseFreeForm(true);
        }
      } catch {
        setUseFreeForm(true);
      }
    })();
    return () => {
      cancelled = true;
    };
  }, [open, patientId]);

  // Reset transient state when re-opened.
  useEffect(() => {
    if (open) {
      setError(null);
      setSuccess(null);
      setGeneratedPassword(null);
      setCreatedLink(null);
      setCopyFlash(null);
      setShowQr(false);
      setQrDataUrl(null);
      setQrError(false);
    }
  }, [open]);

  // Lazy QR generation: only encode when the user asks for the QR
  // (showQr === true) and we have a freshly created link. Generation
  // is async (qrcode lib returns a Promise<string>) so we keep the
  // result in state and skip re-runs when the link/url hasn't changed.
  useEffect(() => {
    if (!showQr || !createdLink) return;
    let cancelled = false;
    setQrError(false);
    void QRCode.toDataURL(createdLink.url, {
      width: 280,
      margin: 1,
      errorCorrectionLevel: "M",
    })
      .then((dataUrl) => {
        if (!cancelled) setQrDataUrl(dataUrl);
      })
      .catch(() => {
        if (!cancelled) setQrError(true);
      });
    return () => {
      cancelled = true;
    };
  }, [showQr, createdLink]);

  // Global Escape close: a keydown handler scoped to the dialog
  // ``<div role="dialog">`` only fires when focus is inside the
  // dialog tree. Listening on ``document`` wins regardless of where
  // focus landed — including the case where the user clicks outside
  // and back, or never tab-focused into a control. Cleaned up on
  // close so a stale listener can't keep callbacks alive.
  useEffect(() => {
    if (!open) return;
    function onKey(e: KeyboardEvent) {
      if (e.key === "Escape") onClose();
    }
    document.addEventListener("keydown", onKey);
    return () => document.removeEventListener("keydown", onKey);
  }, [open, onClose]);

  const selectedContact = useMemo<PatientContact | null>(() => {
    if (useFreeForm) return null;
    return contacts.find((c) => (c.id || c.email || "") === recipientFromList) || null;
  }, [contacts, recipientFromList, useFreeForm]);

  const recipientName = useFreeForm ? freeName.trim() : selectedContact?.label || "";
  const recipientEmail = useFreeForm ? freeEmail.trim() : (selectedContact?.email || "").trim();

  const recipientReady =
    deliveryMode === "copy"
      ? // For copy mode we still capture the recipient name + email so
        // the audit row + landing page can show "destinato a Dr. X"
        // even if the email is delivered by hand. Only the email is
        // strictly required (so the share-link row carries it).
        recipientEmail.length > 0
      : recipientEmail.length > 0;

  /**
   * Build the prefilled mailto: string for the copy-mode delivery.
   * Computed lazily from the created link + custom message so the
   * post-submit view can re-derive it on every "Apri client mail"
   * click (the URL never changes, but the user might tweak the
   * custom message after creation in a future iteration).
   */
  function buildMailtoUrl(link: ShareLink): string {
    const subject = encodeURIComponent(
      t("mailtoSubject", { label: studyLabel ? `: ${studyLabel}` : "" }),
    );
    const intro = customMessage ? `${customMessage}\n\n` : "";
    const studyLine = studyLabel ? `${t("mailtoBodyStudyLine", { label: studyLabel })}\n` : "";
    const expiryLine = link.expires_at
      ? `${t("mailtoBodyExpiryLine", {
          date: new Date(link.expires_at).toLocaleDateString(locale, {
            day: "numeric",
            month: "long",
            year: "numeric",
          }),
        })}\n`
      : "";
    const deidentifyLine = link.deidentify ? `${t("mailtoBodyDeidentified")}\n` : "";
    const pwdHint = link.requires_password ? `${t("mailtoBodyPasswordHint")}\n` : "";
    // ``link.url`` comes back absolute from the backend now (mig
    // round bumped settings.public_frontend_url default). The
    // earlier bug where this was a path-only URL leaking into the
    // mailto: body is fixed at the source.
    const body = encodeURIComponent(
      `${intro}${studyLine}${t("mailtoBodyOpen")}\n${link.url}\n\n${expiryLine}${deidentifyLine}${pwdHint}`,
    );
    return `mailto:${encodeURIComponent(recipientEmail)}?subject=${subject}&body=${body}`;
  }

  /**
   * Try the modern Clipboard API first; fall back to the
   * ``execCommand("copy")`` legacy path (works in older Safari and
   * in non-HTTPS contexts where ``navigator.clipboard`` is gated).
   * The copy operation writes the absolute share URL exactly as
   * the recipient should see it.
   */
  async function copyLinkToClipboard(url: string): Promise<boolean> {
    if (navigator.clipboard?.writeText) {
      try {
        await navigator.clipboard.writeText(url);
        return true;
      } catch {
        // Fall through to legacy path.
      }
    }
    try {
      const ta = document.createElement("textarea");
      ta.value = url;
      ta.setAttribute("readonly", "");
      ta.style.position = "fixed";
      ta.style.opacity = "0";
      document.body.appendChild(ta);
      ta.select();
      document.execCommand("copy");
      ta.remove();
      return true;
    } catch {
      return false;
    }
  }

  /**
   * Mailto navigation: ``window.open(mailto, "_blank")`` opens
   * about:blank in modern Chrome (and similar browsers) instead of
   * the OS mail client because the popup blocker treats the
   * brand-new tab as the resource and never resolves the
   * mailto:. Setting ``window.location.href`` triggers the
   * registered protocol handler in-tab; the browser opens the
   * mail client and the original tab snaps back to the dialog
   * (we never navigate away from this page).
   */
  function openMailto(link: ShareLink): void {
    if (typeof window === "undefined") return;
    window.location.href = buildMailtoUrl(link);
  }

  async function handleCopyAgain(link: ShareLink) {
    const ok = await copyLinkToClipboard(link.url);
    setCopyFlash(ok ? "copied" : "failed");
    // Auto-clear so a later click can re-flash visibly.
    window.setTimeout(() => setCopyFlash(null), 1500);
  }

  async function handleSubmit() {
    if (!recipientReady) {
      setError(t("errorNoEmailOnLink"));
      return;
    }
    setBusy(true);
    setError(null);
    setSuccess(null);
    setGeneratedPassword(null);
    setCreatedLink(null);
    try {
      // 1) Create the share link with the chosen options. The backend
      //    auto-resolves ``deidentify`` to ON for external grants when
      //    we pass null; we always pass an explicit boolean here so
      //    the user's toggle is the source of truth (no surprise).
      // AI sponsorship cap (patient kind only). Convert EUR → cents,
      // bail with a clear error if the user typed garbage rather than
      // silently sending a NaN to the backend (which would 422 with a
      // generic Pydantic message).
      let aiCapCents: number | null = null;
      if (kind === "patient" && aiSponsor) {
        const eur = Number.parseFloat(aiCapEur);
        if (!Number.isFinite(eur) || eur <= 0) {
          throw new Error(t("aiSponsorInvalidAmount"));
        }
        aiCapCents = Math.round(eur * 100);
      }
      const sharePayload = {
        access_level: "viewer",
        download: true,
        target: { kind: "link_public" },
        expires_in_hours: EXPIRY_HOURS[expiry],
        autogen_password: autogenPassword,
        deidentify,
        recipient_name: recipientName || null,
        recipient_email: recipientEmail || null,
        label: label.trim() || null,
        ai_sponsorship_cap_cents: aiCapCents,
      };
      const created =
        kind === "folder"
          ? await foldersApi.shareLink(studyId, sharePayload)
          : kind === "patient"
            ? await patientsApi.createShare(studyId, sharePayload)
            : await studiesApi.share(studyId, sharePayload);

      const link = created as ShareLink;
      if (link.generated_password) {
        setGeneratedPassword(link.generated_password);
      }
      setCreatedLink(link);

      if (deliveryMode === "email") {
        // Pass the active UI locale so the backend renders the email
        // body + subject in the same language the grantor was reading
        // when they hit Send. Cookie + Accept-Language are fallbacks
        // server-side; the explicit field wins so a user who toggled
        // the LanguageSwitcher in this tab gets coherent copy.
        const apiLocale = locale === "en" ? "en" : "it";
        const result = await studiesApi.notifyShare(
          link.id,
          customMessage.trim() || null,
          apiLocale,
        );
        setSuccess(t("successSent", { to: result.to }));
      } else {
        // Copy mode: write the absolute URL to clipboard, then
        // navigate to mailto: so the OS mail client opens with a
        // pre-filled draft. The dialog stays mounted (we set
        // ``createdLink`` so the post-submit view replaces the form
        // with a "Copia di nuovo" + "Apri client mail" panel — the
        // recipient who lost focus on the clipboard between Cmd+C
        // and Cmd+V can re-grab the link from there).
        const ok = await copyLinkToClipboard(link.url);
        setCopyFlash(ok ? "copied" : "failed");
        openMailto(link);
        setSuccess(t("successCopied"));
      }
    } catch (e) {
      setError(e instanceof ApiError ? t("errorGeneric", { message: e.message }) : String(e));
    } finally {
      setBusy(false);
    }
  }

  if (!open) return null;
  // SSR guard: createPortal needs ``document``; render nothing on the
  // first server pass and let hydration mount the portal client-side.
  if (typeof document === "undefined") return null;

  // Render the overlay through a portal mounted at ``document.body``
  // so no ancestor stacking context (the patient page wraps the
  // study card in several flex/grid layers, and the
  // ``ClinicalNotesSticky`` section above it uses
  // ``isolation: isolate`` to keep the folder grid behind it) can
  // trap our z-index. Without the portal a ``position: fixed``
  // descendant of an ``isolation: isolate`` ancestor stays inside
  // that ancestor's stacking context and the sticky notes (z-index
  // 100 in their own context) end up painting above us — which is
  // exactly the bug the e2e spec
  // ``e2e/send-study-dialog.spec.ts`` pins.
  return createPortal(
    // biome-ignore lint/a11y/useSemanticElements: native <dialog> has different open/close semantics; we manage focus + escape via the document keydown handler above.
    // biome-ignore lint/a11y/useKeyWithClickEvents: the click target is the backdrop; keyboard close is handled globally by the document listener in the effect above.
    <div
      role="dialog"
      aria-modal="true"
      style={{
        position: "fixed",
        inset: 0,
        background: "rgba(0,0,0,0.4)",
        display: "flex",
        alignItems: "center",
        justifyContent: "center",
        zIndex: 1200,
      }}
      onClick={(e) => {
        if (e.target === e.currentTarget) onClose();
      }}
    >
      <div
        style={{
          background: "var(--bv-card-bg, #fff)",
          color: "var(--bv-fg, inherit)",
          borderRadius: 8,
          maxWidth: 540,
          width: "92%",
          maxHeight: "92vh",
          overflowY: "auto",
          padding: "1.25rem",
          border: "1px solid var(--border, #ccc)",
          boxShadow: "0 12px 40px rgba(0,0,0,0.18)",
        }}
      >
        <header style={{ marginBottom: "0.75rem" }}>
          <h2 style={{ margin: 0, fontSize: "1.05rem" }}>
            {createdLink ? t("successHeading") : t("title")}
          </h2>
          <p style={{ margin: "0.25rem 0 0", fontSize: "0.85rem", opacity: 0.75 }}>
            {createdLink ? t("successHint") : t("subtitle")}
          </p>
        </header>

        {!createdLink && (
          <>
            {/* Recipient */}
            <Section title={t("recipientSection")}>
              {contacts.length > 0 && (
                <label
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "0.5rem",
                    marginBottom: "0.4rem",
                  }}
                >
                  <input
                    type="radio"
                    checked={!useFreeForm}
                    onChange={() => setUseFreeForm(false)}
                  />
                  <span style={{ fontSize: "0.85rem" }}>{t("recipientFromContacts")}</span>
                </label>
              )}
              {!useFreeForm && contacts.length > 0 && (
                <select
                  value={recipientFromList}
                  onChange={(e) => setRecipientFromList(e.target.value)}
                  style={{
                    width: "100%",
                    padding: "0.4rem",
                    marginBottom: "0.5rem",
                  }}
                >
                  {contacts.map((c) => (
                    <option key={c.id || c.email} value={c.id || c.email || ""}>
                      {c.label} {c.email ? `<${c.email}>` : ""}
                      {c.relationship ? ` — ${c.relationship}` : ""}
                    </option>
                  ))}
                </select>
              )}
              {contacts.length === 0 && (
                <p style={{ fontSize: "0.8rem", opacity: 0.7, margin: "0 0 0.5rem" }}>
                  {t("recipientNoneFound")}
                </p>
              )}
              <label
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "0.5rem",
                  marginBottom: "0.4rem",
                }}
              >
                <input type="radio" checked={useFreeForm} onChange={() => setUseFreeForm(true)} />
                <span style={{ fontSize: "0.85rem" }}>{t("recipientFreeForm")}</span>
              </label>
              {useFreeForm && (
                <div style={{ display: "grid", gap: "0.4rem", marginBottom: "0.5rem" }}>
                  <input
                    type="text"
                    placeholder={t("recipientName")}
                    value={freeName}
                    onChange={(e) => setFreeName(e.target.value)}
                    style={{ padding: "0.4rem" }}
                  />
                  <input
                    type="email"
                    placeholder={t("recipientEmail")}
                    value={freeEmail}
                    onChange={(e) => setFreeEmail(e.target.value)}
                    style={{ padding: "0.4rem" }}
                  />
                </div>
              )}
              <label style={{ display: "block", fontSize: "0.8rem", marginTop: "0.5rem" }}>
                <span style={{ display: "block", marginBottom: "0.25rem", opacity: 0.8 }}>
                  {t("labelInputTitle")}
                </span>
                <input
                  type="text"
                  placeholder={t("labelInputPlaceholder")}
                  value={label}
                  onChange={(e) => setLabel(e.target.value)}
                  maxLength={120}
                  style={{ width: "100%", padding: "0.4rem" }}
                />
              </label>
            </Section>

            {/* Privacy */}
            <Section title={t("deidentifySection")}>
              <label
                style={{
                  display: "flex",
                  alignItems: "flex-start",
                  gap: "0.5rem",
                  marginBottom: "0.3rem",
                }}
              >
                <input
                  type="radio"
                  checked={deidentify}
                  onChange={() => setDeidentify(true)}
                  style={{ marginTop: 3 }}
                />
                <span>
                  <span style={{ fontSize: "0.9rem" }}>{t("deidentifyOn")}</span>
                  <span
                    style={{
                      display: "block",
                      fontSize: "0.78rem",
                      opacity: 0.75,
                    }}
                  >
                    {t("deidentifyHint")}
                  </span>
                </span>
              </label>
              <label
                style={{
                  display: "flex",
                  alignItems: "flex-start",
                  gap: "0.5rem",
                }}
              >
                <input
                  type="radio"
                  checked={!deidentify}
                  onChange={() => setDeidentify(false)}
                  style={{ marginTop: 3 }}
                />
                <span>
                  <span style={{ fontSize: "0.9rem" }}>{t("deidentifyOff")}</span>
                  {!deidentify && (
                    <span
                      style={{
                        display: "block",
                        fontSize: "0.78rem",
                        color: "var(--bv-warning, #b45309)",
                      }}
                    >
                      ⚠ {t("deidentifyOffWarning")}
                    </span>
                  )}
                </span>
              </label>
            </Section>

            {/* Expiry + password */}
            <Section title={t("expirySection")}>
              <div style={{ display: "flex", gap: "0.4rem", flexWrap: "wrap" }}>
                {(
                  [
                    ["week", "expiryWeek"],
                    ["month1", "expiryMonth1"],
                    ["month3", "expiryMonth3"],
                    ["month6", "expiryMonth6"],
                    ["year", "expiryYear"],
                  ] as const
                ).map(([opt, key]) => (
                  <label
                    key={opt}
                    style={{
                      display: "inline-flex",
                      alignItems: "center",
                      gap: "0.3rem",
                      fontSize: "0.85rem",
                    }}
                  >
                    <input type="radio" checked={expiry === opt} onChange={() => setExpiry(opt)} />
                    {t(key)}
                  </label>
                ))}
              </div>
              <p style={{ fontSize: "0.75rem", opacity: 0.7, margin: "0.35rem 0 0" }}>
                {t("expiryRenewableHint")}
              </p>
            </Section>

            <Section title={t("passwordSection")}>
              <label
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "0.4rem",
                  fontSize: "0.85rem",
                  marginBottom: "0.3rem",
                }}
              >
                <input
                  type="radio"
                  checked={autogenPassword}
                  onChange={() => setAutogenPassword(true)}
                />
                {t("passwordAutogen")}
              </label>
              <label
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "0.4rem",
                  fontSize: "0.85rem",
                }}
              >
                <input
                  type="radio"
                  checked={!autogenPassword}
                  onChange={() => setAutogenPassword(false)}
                />
                {t("passwordNone")}
              </label>
            </Section>

            {/* AI sponsorship cap. Patient-scope only — the backend
            materialises the WalletSponsorship row when the recipient
            claims an anonymous link, scoped to the shared patient.
            For study/folder shares the sponsorship would land on the
            study's parent patient (the backend lifts that
            automatically for studies; folders not yet wired) so
            we hide the affordance to avoid surprising the user. */}
            {kind === "patient" && (
              <Section title={t("aiSponsorLegend")}>
                <label
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "0.4rem",
                    fontSize: "0.85rem",
                    marginBottom: "0.3rem",
                  }}
                >
                  <input
                    type="checkbox"
                    checked={aiSponsor}
                    onChange={(e) => setAiSponsor(e.target.checked)}
                  />
                  {t("aiSponsorEnable")}
                </label>
                {aiSponsor ? (
                  <div
                    style={{
                      marginTop: "0.4rem",
                      display: "flex",
                      flexWrap: "wrap",
                      gap: "0.4rem",
                      alignItems: "center",
                    }}
                  >
                    {[2, 5, 10, 25].map((eur) => (
                      <button
                        key={eur}
                        type="button"
                        className={aiCapEur === eur.toFixed(2) ? "button" : "ghost"}
                        onClick={() => setAiCapEur(eur.toFixed(2))}
                        aria-pressed={aiCapEur === eur.toFixed(2)}
                        style={{ padding: "0.25rem 0.6rem", fontSize: "0.85rem" }}
                      >
                        €{eur}
                      </button>
                    ))}
                    <span style={{ fontSize: "0.85rem", opacity: 0.7 }}>{t("aiSponsorOr")}</span>
                    <input
                      type="number"
                      min="0.01"
                      step="0.01"
                      value={aiCapEur}
                      onChange={(e) => setAiCapEur(e.target.value)}
                      aria-label={t("aiSponsorCustomLabel")}
                      style={{ width: "5.5rem", padding: "0.25rem 0.4rem" }}
                    />
                    <span style={{ fontSize: "0.85rem" }}>€</span>
                    <p
                      style={{
                        width: "100%",
                        margin: "0.4rem 0 0",
                        fontSize: "0.75rem",
                        opacity: 0.75,
                      }}
                    >
                      {t("aiSponsorHint")}
                    </p>
                  </div>
                ) : (
                  <p style={{ margin: "0.3rem 0 0", fontSize: "0.75rem", opacity: 0.7 }}>
                    {t("aiSponsorOffHint")}
                  </p>
                )}
              </Section>
            )}

            {/* Delivery */}
            <Section title={t("deliverySection")}>
              <label
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "0.4rem",
                  fontSize: "0.85rem",
                  marginBottom: "0.3rem",
                }}
              >
                <input
                  type="radio"
                  checked={deliveryMode === "email"}
                  onChange={() => setDeliveryMode("email")}
                />
                {t("deliveryEmailFromBv")}
              </label>
              <label
                style={{
                  display: "flex",
                  alignItems: "center",
                  gap: "0.4rem",
                  fontSize: "0.85rem",
                }}
              >
                <input
                  type="radio"
                  checked={deliveryMode === "copy"}
                  onChange={() => setDeliveryMode("copy")}
                />
                {t("deliveryCopyLink")}
              </label>
              <p style={{ fontSize: "0.78rem", opacity: 0.7, margin: "0.3rem 0 0" }}>
                {deliveryMode === "email" ? t("deliveryHintEmail") : t("deliveryHintCopy")}
              </p>
              <label
                htmlFor="send-study-custom-message"
                style={{
                  display: "block",
                  fontSize: "0.85rem",
                  margin: "0.5rem 0 0.25rem",
                }}
              >
                {t("customMessage")}
              </label>
              <textarea
                id="send-study-custom-message"
                rows={3}
                value={customMessage}
                onChange={(e) => setCustomMessage(e.target.value)}
                placeholder={t("customMessagePlaceholder")}
                style={{ width: "100%", padding: "0.4rem", resize: "vertical" }}
              />
            </Section>
          </>
        )}

        {/* Footer */}
        {generatedPassword && (
          <div
            style={{
              border: "1px solid var(--bv-warning, #b45309)",
              borderRadius: 6,
              padding: "0.5rem 0.6rem",
              background: "var(--bv-warning-soft, #fef3c7)",
              color: "var(--bv-fg, inherit)",
              marginBottom: "0.6rem",
            }}
          >
            <div style={{ fontWeight: 600, fontSize: "0.85rem" }}>{t("successPasswordOnce")}</div>
            <code
              style={{
                display: "block",
                fontFamily: "var(--bv-mono, monospace)",
                fontSize: "0.95rem",
                padding: "0.25rem 0",
                userSelect: "all",
                wordBreak: "break-all",
              }}
            >
              {generatedPassword}
            </code>
          </div>
        )}
        {/* Success view. Shown for both delivery modes once the share
            link has been created so the user can: re-copy if the
            clipboard was lost, re-open the mail client, or display a
            QR for in-person handoff. The form sections above are
            collapsed (createdLink gate) so this becomes the single
            visible payload — no scrolling to find the link. */}
        {createdLink && (
          <div
            style={{
              border: "1px solid var(--bv-card-border, #e5e7eb)",
              borderRadius: 8,
              padding: "0.75rem 0.85rem",
              marginBottom: "0.6rem",
              background: "var(--bv-bg-soft, #fafafa)",
            }}
          >
            <div
              style={{
                fontSize: "0.8rem",
                fontWeight: 600,
                marginBottom: "0.35rem",
              }}
            >
              {t("createdLinkLabel")}
            </div>
            <textarea
              readOnly
              value={createdLink.url}
              onFocus={(e) => e.currentTarget.select()}
              style={{
                width: "100%",
                fontFamily: "var(--bv-mono, monospace)",
                fontSize: "0.82rem",
                padding: "0.4rem",
                resize: "none",
                border: "1px solid var(--bv-card-border, #e5e7eb)",
                borderRadius: 4,
                background: "var(--bv-card-bg, #fff)",
              }}
              rows={2}
            />
            <div
              style={{
                display: "flex",
                gap: "0.5rem",
                marginTop: "0.55rem",
                alignItems: "center",
                flexWrap: "wrap",
              }}
            >
              <button
                type="button"
                onClick={() => void handleCopyAgain(createdLink)}
                style={{ fontSize: "0.85rem" }}
              >
                {t("copyAgain")}
              </button>
              <button
                type="button"
                onClick={() => openMailto(createdLink)}
                style={{ fontSize: "0.85rem" }}
              >
                {t("openMailClient")}
              </button>
              <button
                type="button"
                className="ghost"
                onClick={() => setShowQr((v) => !v)}
                aria-expanded={showQr}
                style={{ fontSize: "0.85rem" }}
              >
                {showQr ? t("hideQr") : t("showQr")}
              </button>
              {copyFlash === "copied" && (
                <span style={{ fontSize: "0.78rem", color: "var(--bv-success, #047857)" }}>
                  ✓ {t("copyFlashOk")}
                </span>
              )}
              {copyFlash === "failed" && (
                <span style={{ fontSize: "0.78rem", color: "var(--bv-warning, #b45309)" }}>
                  ⚠ {t("copyFlashFailed")}
                </span>
              )}
            </div>
            {showQr && (
              <div
                style={{
                  marginTop: "0.7rem",
                  padding: "0.6rem",
                  borderRadius: 6,
                  border: "1px solid var(--bv-card-border, #e5e7eb)",
                  background: "var(--bv-card-bg, #fff)",
                  display: "flex",
                  flexDirection: "column",
                  alignItems: "center",
                  gap: "0.4rem",
                }}
              >
                {qrError ? (
                  <p
                    style={{
                      margin: 0,
                      fontSize: "0.8rem",
                      color: "var(--bv-warning, #b45309)",
                    }}
                  >
                    ⚠ {t("qrFailed")}
                  </p>
                ) : qrDataUrl ? (
                  <>
                    <img
                      src={qrDataUrl}
                      alt={t("qrInstruction")}
                      width={220}
                      height={220}
                      style={{ display: "block", imageRendering: "pixelated" }}
                    />
                    <p
                      style={{
                        margin: 0,
                        fontSize: "0.78rem",
                        opacity: 0.75,
                        textAlign: "center",
                      }}
                    >
                      {t("qrInstruction")}
                    </p>
                  </>
                ) : (
                  <p style={{ margin: 0, fontSize: "0.8rem", opacity: 0.7 }}>{t("submitting")}</p>
                )}
              </div>
            )}
          </div>
        )}
        {error && (
          <p className="error" style={{ fontSize: "0.85rem" }}>
            {error}
          </p>
        )}
        {success && !error && (
          <p style={{ fontSize: "0.85rem", color: "var(--bv-success, #047857)" }}>{success}</p>
        )}
        {/* Discoverability hand-off: every newly created share is
            tracked in the patient page's "Condivisioni" tab (the
            standalone /patients/{id}/shares URL also works but keeps
            the user out of context). Deep-link to the tab via
            ``?view=shares`` so closing the dialog takes them
            straight to the management table without a route change.
            User had reported "non vedo come cancellare/editare/
            monitorare" because the path was hard to find. */}
        {createdLink && (
          <p style={{ fontSize: "0.8rem", marginTop: "0.4rem" }}>
            <Link
              href={`/patients/${patientId}?view=shares`}
              onClick={onClose}
              style={{ color: "var(--bv-accent, #2563eb)" }}
            >
              {t("manageSharesLink")}
            </Link>
          </p>
        )}

        <div
          style={{
            display: "flex",
            justifyContent: "flex-end",
            gap: "0.5rem",
            marginTop: "0.75rem",
          }}
        >
          {createdLink && (
            <button
              type="button"
              className="ghost"
              onClick={() => {
                setCreatedLink(null);
                setSuccess(null);
                setGeneratedPassword(null);
                setShowQr(false);
                setQrDataUrl(null);
                setQrError(false);
              }}
            >
              {t("actionCreateAnother")}
            </button>
          )}
          <button type="button" className="ghost" onClick={onClose}>
            {createdLink || success ? "OK" : "Annulla"}
          </button>
          {!createdLink && !success && (
            <button type="button" onClick={handleSubmit} disabled={busy || !recipientReady}>
              {busy
                ? t("submitting")
                : deliveryMode === "email"
                  ? t("submitSend")
                  : t("submitCreateAndCopy")}
            </button>
          )}
        </div>
      </div>
    </div>,
    document.body,
  );
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: "0.75rem" }}>
      <h3
        style={{
          margin: "0 0 0.3rem",
          fontSize: "0.78rem",
          textTransform: "uppercase",
          letterSpacing: "0.05em",
          opacity: 0.7,
        }}
      >
        {title}
      </h3>
      {children}
    </section>
  );
}
