"""Generate ``services/deid/ps315_e11.py`` from the NEMA PS3.15 DocBook XML.

One-time (per DICOM edition) dev tool — the OUTPUT module is committed, so
neither runtime nor CI ever touches the network. Regenerating for a new
edition is a re-run + review of the diff; the protectiveness tests
(``tests/test_ps315_table.py``) and the TCIA Pseudo-PHI header corpus are the
safety net.

    uv run python scripts/gen_ps315_table.py --edition 2026b
    uv run python scripts/gen_ps315_table.py --edition 2026b --offline /path/part15.xml

The parser is deliberately brittle: an unexpected column count, an unknown
action code, or an unrecognised tag pattern is a HARD error — a future edition
must fail loudly here rather than silently mis-generate the confidentiality
table.
"""

from __future__ import annotations

import argparse
import hashlib
import re
import sys
import urllib.request
import xml.etree.ElementTree as ET
from pathlib import Path

NS = "{http://docbook.org/ns/docbook}"
XML_ID = "{http://www.w3.org/XML/1998/namespace}id"

URL_TEMPLATE = "https://dicom.nema.org/medical/dicom/{edition}/source/docbook/part15/part15.xml"

# Every action code Table E.1-1 is allowed to carry (basic + option columns).
# 2026b uses: basic {D,U,X,X/D,X/Z,X/Z/D,X/Z/U*,Z,Z/D}, options {C,K}. The
# superset below tolerates historical combos; anything else is a hard error.
KNOWN_CODES = frozenset(
    {"", "C", "D", "K", "U", "X", "Z", "X/D", "X/Z", "X/Z/D", "X/Z/U*", "Z/D", "K/C", "X/D/U"}
)

_TAG_RE = re.compile(r"^\(([0-9A-Fa-f]{4}),([0-9A-Fa-f]{4})\)$")
# The 4 known non-literal tag rows. The private-attributes row is informational
# (the executor's private-tag branch + safe_private implement it); the
# repeating-group rows become mask rules in profile_table.
SPECIAL_TAGS = {
    "(50xx,xxxx)": "curve_50xx",
    "(60xx,3000)": "overlay_data_60xx",
    "(60xx,4000)": "overlay_comments_60xx",
    "(gggg,eeee) where gggg is odd": "private",
}

MIN_ROWS = 550  # sanity floor; 2026b has 655

HEADER = '''"""DICOM PS3.15 Table E.1-1 — GENERATED by backend/scripts/gen_ps315_table.py.

DO NOT EDIT BY HAND. Regenerate with:

    uv run python scripts/gen_ps315_table.py --edition {edition}

Pure data: one tuple per table row, raw standard action codes as strings. The
policy mapping (code -> engine Action, overrides, option relaxation) lives in
``profile_table.py`` so regenerating for a new edition never re-encodes policy.

Row shape:
    (tag:int|None, special:str|None, name:str, keyword:str, retired:bool,
     in_std_iod:bool, basic:str, rtn_safe_priv:str, rtn_uids:str,
     rtn_dev_id:str, rtn_inst_id:str, rtn_pat_chars:str, rtn_full_dates:str,
     rtn_mod_dates:str, clean_desc:str, clean_struct:str, clean_graph:str)

``tag`` is ``(group << 16) | element``; the 4 non-literal rows carry
``special`` instead ({specials}).
"""

from __future__ import annotations

PS315_TABLE_VERSION = "{edition}"
PS315_SOURCE_URL = "{url}"
PS315_SOURCE_SHA256 = "{sha256}"

Row = tuple[
    int | None, str | None, str, str, bool, bool,
    str, str, str, str, str, str, str, str, str, str, str,
]

ROWS: tuple[Row, ...] = (
'''


def _cell_text(td: ET.Element) -> str:
    return " ".join("".join(td.itertext()).split())


def parse_table(xml_path: Path) -> list[tuple]:
    tree = ET.parse(xml_path)
    table = next(
        (t for t in tree.getroot().iter(f"{NS}table") if t.get(XML_ID) == "table_E.1-1"),
        None,
    )
    if table is None:
        sys.exit("FATAL: table_E.1-1 not found in the DocBook XML")

    rows: list[tuple] = []
    seen_tags: set[int] = set()
    for tr in table.findall(f".//{NS}tbody/{NS}tr"):
        cells = [_cell_text(td) for td in tr.findall(f"{NS}td")]
        if len(cells) != 15:
            sys.exit(f"FATAL: expected 15 cells, got {len(cells)}: {cells[:3]}...")
        name, tag_text, retired, in_iod, basic, *option_cols = cells
        for code in [basic, *option_cols]:
            if code not in KNOWN_CODES:
                sys.exit(f"FATAL: unknown action code {code!r} on row {name!r}")

        m = _TAG_RE.match(tag_text)
        if m:
            tag = (int(m.group(1), 16) << 16) | int(m.group(2), 16)
            special = None
            if tag in seen_tags:
                sys.exit(f"FATAL: duplicate tag {tag_text} ({name!r})")
            seen_tags.add(tag)
            try:
                from pydicom.datadict import keyword_for_tag

                keyword = keyword_for_tag(tag) or ""
            except ImportError:
                keyword = ""
        elif tag_text in SPECIAL_TAGS:
            tag, special, keyword = None, SPECIAL_TAGS[tag_text], ""
        else:
            sys.exit(f"FATAL: unrecognised tag pattern {tag_text!r} on row {name!r}")

        rows.append(
            (
                tag,
                special,
                name,
                keyword,
                retired.upper().startswith("Y"),
                in_iod.upper().startswith("Y"),
                basic,
                *option_cols,
            )
        )

    if len(rows) < MIN_ROWS:
        sys.exit(f"FATAL: only {len(rows)} rows parsed (expected >= {MIN_ROWS})")
    missing = set(SPECIAL_TAGS.values()) - {r[1] for r in rows if r[1]}
    if missing:
        sys.exit(f"FATAL: expected special rows missing: {missing}")
    # Deterministic ordering: literal tags sorted, specials at the end.
    rows.sort(key=lambda r: (r[0] is None, r[0] if r[0] is not None else 0, r[1] or ""))
    return rows


def emit(rows: list[tuple], *, edition: str, url: str, sha256: str, out: Path) -> None:
    lines = [
        HEADER.format(
            edition=edition,
            url=url,
            sha256=sha256,
            specials=", ".join(sorted(set(SPECIAL_TAGS.values()))),
        )
    ]
    for r in rows:
        tag = f"0x{r[0]:08X}" if r[0] is not None else "None"
        rest = ", ".join(repr(v) for v in r[1:])
        lines.append(f"    ({tag}, {rest}),\n")
    lines.append(')\n\n__all__ = ["PS315_SOURCE_SHA256", "PS315_SOURCE_URL", ')
    lines.append('"PS315_TABLE_VERSION", "ROWS", "Row"]\n')
    out.write_text("".join(lines))


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--edition", default="2026b", help="Pinned DICOM edition (archived URL).")
    ap.add_argument("--offline", type=Path, default=None, help="Pre-downloaded part15.xml.")
    ap.add_argument(
        "--out",
        type=Path,
        default=Path(__file__).resolve().parents[1] / "src/bvphoenix/services/deid/ps315_e11.py",
    )
    args = ap.parse_args()

    url = URL_TEMPLATE.format(edition=args.edition)
    if args.offline:
        xml_path = args.offline
    else:
        xml_path = Path(f"/tmp/part15-{args.edition}.xml")
        print(f"downloading {url} ...")
        urllib.request.urlretrieve(url, xml_path)

    sha256 = hashlib.sha256(xml_path.read_bytes()).hexdigest()
    rows = parse_table(xml_path)
    emit(rows, edition=args.edition, url=url, sha256=sha256, out=args.out)
    literal = sum(1 for r in rows if r[0] is not None)
    print(f"wrote {args.out}: {len(rows)} rows ({literal} literal tags), sha256={sha256[:12]}...")


if __name__ == "__main__":
    main()
