"""Construct S3 keys for series-derived blobs (packed volumes, MIPs).

Why this module exists
======================
Earlier code keyed derivatives on the DICOM ``SeriesInstanceUID``
directly, e.g. ``volumes/<series_instance_uid>.f32``. That UID comes
from whatever scanner / RIS produced the source DICOM and is **not**
authoritative across BitVision tenants:

* Two patients on the same deployment can carry the same DICOM
  ``SeriesInstanceUID`` if their data was generated by the same
  scanner using a buggy UID-generation policy or if a malicious
  upload crafts a colliding UID. Either way, ``PUT
  volumes/<uid>.f32`` overwrites the other patient's blob.
* A subsequent ``GET volumes/<uid>.f32`` then returns the wrong
  patient's bytes — a cross-tenant data leak / data-integrity
  break the read-side authorization layer cannot catch (the bytes
  *do* exist, the wrong content is served).

The remediation is to key derivatives on values BitVision
controls: the ``Series.id`` (an internal UUID, collision-impossible
by construction) plus the ``patient_id`` prefix for traceability.
DICOM UIDs are kept only on the row metadata (``Series.series_instance_uid``)
where they belong as descriptive fields, not as storage addresses.

Layout
======
::

    patients/<patient_id>/series/<series_id>/volume.f32                   # full-res
    patients/<patient_id>/series/<series_id>/volume.earl-<N>.f32          # EARL-corrected
    patients/<patient_id>/series/<series_id>/volume.preview.f32           # 1/8-res preview
    patients/<patient_id>/series/<series_id>/mip-<N>f-<H>h.png            # rotating MIP sprite

For studies with no patient yet (``ImagingStudy.patient_id IS NULL``,
seen on freshly imported data before patient assignment) the prefix
becomes ``unassigned/`` instead of ``patients/<patient_id>/``. Once
the patient is assigned, future writes pick up the correct
prefix; existing blobs continue serving from their recorded
``Derivative.s3_key`` until they are re-packed.

Migration
=========
The Derivative read path always loads the actual ``s3_key`` from
the DB row, so flipping the write scheme is non-breaking: rows
written under the legacy flat scheme keep serving from their
recorded keys; rows written after this fix use the safe scheme.
The legacy keys can be removed at the operator's discretion (e.g.
through a bulk ``s3 rm`` over the legacy ``volumes/`` /
``mip-sprites/`` prefixes); the next viewer access re-packs each
affected series under the safe scheme.
"""

from __future__ import annotations

import uuid

__all__ = [
    "mip_sprite_key",
    "volume_earl_key",
    "volume_key",
    "volume_preview_key",
    "volume_stack_earl_key",
    "volume_stack_key",
]


def _series_prefix(patient_id: uuid.UUID | None, series_id: uuid.UUID | str) -> str:
    """Build the per-series directory prefix.

    ``patient_id`` is normally set; ``None`` only for orphan studies
    (no patient assigned yet) — those land under ``unassigned/``
    until the patient link is created. ``series_id`` accepts either
    a UUID instance or its canonical string form so callers don't
    have to coerce.
    """
    sid = str(series_id)
    if patient_id is None:
        return f"unassigned/series/{sid}"
    return f"patients/{patient_id}/series/{sid}"


def volume_key(*, patient_id: uuid.UUID | None, series_id: uuid.UUID | str) -> str:
    """S3 key for the full-resolution packed Float32 volume."""
    return f"{_series_prefix(patient_id, series_id)}/volume.f32"


def volume_earl_key(
    *,
    patient_id: uuid.UUID | None,
    series_id: uuid.UUID | str,
    earl_fwhm_mm: float,
) -> str:
    """S3 key for an EARL-harmonized volume.

    ``earl_fwhm_mm`` is the target effective PSF FWHM in mm; we
    encode it as decimillimetres (``round(earl_fwhm_mm * 10)``) so
    the same key matches across float-rounding wobble in the input
    parameter.
    """
    tag = round(earl_fwhm_mm * 10)
    return f"{_series_prefix(patient_id, series_id)}/volume.earl-{tag}.f32"


def volume_stack_key(
    *,
    patient_id: uuid.UUID | None,
    series_id: uuid.UUID | str,
    stack_index: int,
) -> str:
    """S3 key for one sub-stack of a multi-stack series (mDIXON W/F/IP/OP,
    multi-echo, DWI b-values; see ``services.volumes.partition_substacks``).

    Stack 0 (the primary/default stack) ALIASES the canonical
    ``volume.f32`` key so single-stack series and legacy readers are
    unaffected; only the extra contrasts (index >= 1) get a suffixed key.
    """
    if stack_index == 0:
        return volume_key(patient_id=patient_id, series_id=series_id)
    return f"{_series_prefix(patient_id, series_id)}/volume.stack-{stack_index}.f32"


def volume_stack_earl_key(
    *,
    patient_id: uuid.UUID | None,
    series_id: uuid.UUID | str,
    stack_index: int,
    earl_fwhm_mm: float,
) -> str:
    """S3 key for an EARL-harmonized sub-stack volume. Stack 0 aliases the
    canonical ``volume.earl-<N>.f32`` key."""
    if stack_index == 0:
        return volume_earl_key(
            patient_id=patient_id, series_id=series_id, earl_fwhm_mm=earl_fwhm_mm
        )
    tag = round(earl_fwhm_mm * 10)
    return f"{_series_prefix(patient_id, series_id)}/volume.stack-{stack_index}.earl-{tag}.f32"


def volume_preview_key(*, patient_id: uuid.UUID | None, series_id: uuid.UUID | str) -> str:
    """S3 key for the 1/8-resolution preview volume."""
    return f"{_series_prefix(patient_id, series_id)}/volume.preview.f32"


def mip_sprite_key(
    *,
    patient_id: uuid.UUID | None,
    series_id: uuid.UUID | str,
    num_frames: int,
    target_height: int,
) -> str:
    """S3 key for a rotating-MIP sprite PNG.

    ``num_frames`` and ``target_height`` are part of the key so that
    different sprite shapes coexist for the same series without
    overwriting each other.
    """
    return f"{_series_prefix(patient_id, series_id)}/mip-{num_frames}f-{target_height}h.png"
