"""PathologySlide — whole-slide imaging entity (vetrini istologici).

Counterpart of ``ImagingStudy`` for histology / pathology data. A row
represents one scanned glass slide: a multi-resolution pyramid (~1-10
GB on disk) of one stained section, linked to its parent ``Patient``
and an optional ``ClinicalEvent`` (``kind = 'pathology_slide'``).

Storage layout (storage isolation per memory
``feedback-storage-isolation``):
* ``s3_source_key`` — the original SVS / NDPI / OME-TIFF / DICOM-WSI
* ``s3_thumbnail_key`` — a ~512 px JPEG generated by pyvips at ingest
* ``s3_macro_key`` — optional 1× overview image (most scanners
  embed one) extracted via OpenSlide associated_images
* ``s3_label_key`` — optional photo of the printed slide label. NOT
  generated by default because the label commonly carries PHI
  (patient name, MRN, date of birth — see spike §6). When written,
  ``label_redacted`` records whether a redaction pass was applied.

License / provenance columns mirror migration 0004 on imaging_studies
so a future OpenData public-pathology connector can reuse the
``services.public_dataset.import_public_dataset`` pattern as-is.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from bvphoenix.db.base import Base
from bvphoenix.db.models._common import uuid_pk


class PathologySlide(Base):
    __tablename__ = "pathology_slides"

    id: Mapped[uuid.UUID] = uuid_pk()
    patient_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("patients.id", ondelete="CASCADE"),
        nullable=False,
    )
    clinical_event_id: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("clinical_events.id", ondelete="CASCADE"),
        nullable=True,
    )
    owner_subject_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("subjects.id", ondelete="RESTRICT"),
        nullable=False,
    )
    owner_org_subject_id: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("subjects.id", ondelete="SET NULL"),
        nullable=True,
    )
    slide_instance_uid: Mapped[str] = mapped_column(String(128), nullable=False)

    # Pathologist-supplied identifiers on the gross specimen.
    block_label: Mapped[str | None] = mapped_column(String(64))
    slide_label: Mapped[str | None] = mapped_column(String(64))
    stain: Mapped[str | None] = mapped_column(String(64))
    scanner_make: Mapped[str | None] = mapped_column(String(64))
    scanner_model: Mapped[str | None] = mapped_column(String(64))
    magnification: Mapped[float | None] = mapped_column(Float)
    mpp_x: Mapped[float | None] = mapped_column(Float)  # micrometres per pixel, base level
    mpp_y: Mapped[float | None] = mapped_column(Float)
    base_width: Mapped[int | None] = mapped_column(Integer)
    base_height: Mapped[int | None] = mapped_column(Integer)
    pyramid_levels: Mapped[int | None] = mapped_column(Integer)
    source_format: Mapped[str] = mapped_column(String(16), nullable=False)

    s3_bucket: Mapped[str] = mapped_column(String(255), nullable=False)
    s3_source_key: Mapped[str] = mapped_column(String(512), nullable=False)
    size_bytes: Mapped[int] = mapped_column(BigInteger, nullable=False)
    content_sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    s3_thumbnail_key: Mapped[str | None] = mapped_column(String(512))
    s3_macro_key: Mapped[str | None] = mapped_column(String(512))
    s3_label_key: Mapped[str | None] = mapped_column(String(512))
    label_redacted: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")

    contribution_tier: Mapped[str] = mapped_column(String(8), nullable=False, server_default="t1")
    is_public: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")
    ingestion_complete: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false"
    )

    # License / provenance — only populated for tier=t4 imports.
    source_collection: Mapped[str | None] = mapped_column(Text)
    source_subject_id: Mapped[str | None] = mapped_column(Text)
    license_spdx: Mapped[str | None] = mapped_column(Text)
    license_url: Mapped[str | None] = mapped_column(Text)
    citation_required: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")
    citation_text: Mapped[str | None] = mapped_column(Text)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    __table_args__ = (
        UniqueConstraint(
            "owner_subject_id",
            "slide_instance_uid",
            name="uq_pathology_slides_owner_uid",
        ),
        Index("ix_pathology_slides_patient", "patient_id"),
        Index("ix_pathology_slides_public", "is_public"),
        Index("ix_pathology_slides_tier", "contribution_tier"),
    )
