"""PathologySlide — whole-slide imaging entity (vetrini istologici).

Counterpart of ``ImagingStudy`` for histology / pathology data. A row
represents one scanned glass slide: a multi-resolution pyramid (~1-10
GB on disk) of one stained section, linked to its parent ``Patient``
and an optional ``ClinicalEvent`` (``kind = 'pathology_slide'``).

Storage layout (storage isolation per memory
``feedback-storage-isolation``):
* ``s3_source_key`` — the original SVS / NDPI / OME-TIFF / DICOM-WSI
* ``s3_thumbnail_key`` — a ~512 px JPEG generated by pyvips at ingest
* ``s3_macro_key`` — optional 1× overview image (most scanners
  embed one) extracted via OpenSlide associated_images
* ``s3_label_key`` — optional photo of the printed slide label. NOT
  generated by default because the label commonly carries PHI
  (patient name, MRN, date of birth — see spike §6). When written,
  ``label_redacted`` records whether a redaction pass was applied.

License / provenance columns mirror migration 0004 on imaging_studies
so a future OpenData public-pathology connector can reuse the
``services.public_dataset.import_public_dataset`` pattern as-is.
"""

from __future__ import annotations

import uuid
from datetime import datetime

from sqlalchemy import (
    BigInteger,
    Boolean,
    CheckConstraint,
    DateTime,
    Float,
    ForeignKey,
    Index,
    Integer,
    String,
    Text,
    UniqueConstraint,
    func,
    text,
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.orm import Mapped, mapped_column

from bvphoenix.db.base import Base
from bvphoenix.db.models._common import uuid_pk


class PathologySlide(Base):
    __tablename__ = "pathology_slides"

    id: Mapped[uuid.UUID] = uuid_pk()
    patient_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("patients.id", ondelete="CASCADE"),
        nullable=False,
    )
    clinical_event_id: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("clinical_events.id", ondelete="CASCADE"),
        nullable=True,
    )
    owner_subject_id: Mapped[uuid.UUID] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("subjects.id", ondelete="RESTRICT"),
        nullable=False,
    )
    owner_org_subject_id: Mapped[uuid.UUID | None] = mapped_column(
        PG_UUID(as_uuid=True),
        ForeignKey("subjects.id", ondelete="SET NULL"),
        nullable=True,
    )
    slide_instance_uid: Mapped[str] = mapped_column(String(128), nullable=False)

    # Pathologist-supplied identifiers on the gross specimen.
    block_label: Mapped[str | None] = mapped_column(String(64))
    slide_label: Mapped[str | None] = mapped_column(String(64))
    stain: Mapped[str | None] = mapped_column(String(64))
    scanner_make: Mapped[str | None] = mapped_column(String(64))
    scanner_model: Mapped[str | None] = mapped_column(String(64))
    magnification: Mapped[float | None] = mapped_column(Float)
    mpp_x: Mapped[float | None] = mapped_column(Float)  # micrometres per pixel, base level
    mpp_y: Mapped[float | None] = mapped_column(Float)
    base_width: Mapped[int | None] = mapped_column(Integer)
    base_height: Mapped[int | None] = mapped_column(Integer)
    pyramid_levels: Mapped[int | None] = mapped_column(Integer)
    source_format: Mapped[str] = mapped_column(String(16), nullable=False)

    # Clinical image class. ``wsi`` = a scanned glass slide (pyramidal,
    # OpenSlide-readable). ``gross`` = a macroscopic photo of the
    # specimen; ``micrograph`` = a static microscopy capture. The last
    # two arrive as ordinary RGB images (no native pyramid) and are read
    # at ingest with Pillow; the tiler builds their pyramid with pyvips
    # so all three classes are viewed through the same deep-zoom path.
    slide_class: Mapped[str] = mapped_column(String(16), nullable=False, server_default="wsi")

    # --- DZI deep-zoom pyramid (Step 2 viewer) ------------------------
    # The ``tile_wsi`` worker renders a DeepZoom tile pyramid into the
    # derivatives bucket (NEVER exposed: storage isolation) and flips
    # ``dzi_ready``. The ``ck_pathology_slides_dzi_ready_complete`` CHECK
    # makes a half-written ready row impossible, so the serving
    # endpoints trust ``dzi_ready`` as a single gate.
    s3_dzi_key: Mapped[str | None] = mapped_column(String(512))
    dzi_ready: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")
    dzi_levels: Mapped[int | None] = mapped_column(Integer)
    dzi_tile_size: Mapped[int | None] = mapped_column(Integer)
    dzi_overlap: Mapped[int | None] = mapped_column(Integer)
    dzi_format: Mapped[str | None] = mapped_column(String(8))
    dzi_generator_version: Mapped[str | None] = mapped_column(String(32))
    # Last tiling failure (code + detail). Distinguishes "never tiled"
    # (NULL) from "tiling failed" (set) so the backfill CLI and the list
    # endpoint can show + selectively retry. NULL on success.
    dzi_error: Mapped[dict | None] = mapped_column(JSONB)

    s3_bucket: Mapped[str] = mapped_column(String(255), nullable=False)
    s3_source_key: Mapped[str] = mapped_column(String(512), nullable=False)
    size_bytes: Mapped[int] = mapped_column(BigInteger, nullable=False)
    content_sha256: Mapped[str] = mapped_column(String(64), nullable=False)
    s3_thumbnail_key: Mapped[str | None] = mapped_column(String(512))
    s3_macro_key: Mapped[str | None] = mapped_column(String(512))
    s3_label_key: Mapped[str | None] = mapped_column(String(512))
    label_redacted: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="true")

    contribution_tier: Mapped[str] = mapped_column(String(8), nullable=False, server_default="t1")
    is_public: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")
    ingestion_complete: Mapped[bool] = mapped_column(
        Boolean, nullable=False, server_default="false"
    )

    # License / provenance — only populated for tier=t4 imports.
    source_collection: Mapped[str | None] = mapped_column(Text)
    source_subject_id: Mapped[str | None] = mapped_column(Text)
    license_spdx: Mapped[str | None] = mapped_column(Text)
    license_url: Mapped[str | None] = mapped_column(Text)
    citation_required: Mapped[bool] = mapped_column(Boolean, nullable=False, server_default="false")
    citation_text: Mapped[str | None] = mapped_column(Text)

    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, server_default=func.now()
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        nullable=False,
        server_default=func.now(),
        onupdate=func.now(),
    )

    __table_args__ = (
        UniqueConstraint(
            "owner_subject_id",
            "slide_instance_uid",
            name="uq_pathology_slides_owner_uid",
        ),
        CheckConstraint(
            "slide_class IN ('wsi','gross','micrograph')",
            name="ck_pathology_slides_slide_class",
        ),
        # A ready DZI MUST carry every descriptor field — half-written
        # ready rows are impossible at the DB layer (same defence-in-depth
        # as ck_pathology_slides_label_redacted_when_present).
        CheckConstraint(
            "dzi_ready = FALSE OR ("
            "s3_dzi_key IS NOT NULL AND dzi_levels IS NOT NULL "
            "AND dzi_tile_size IS NOT NULL AND dzi_format IS NOT NULL "
            "AND dzi_generator_version IS NOT NULL)",
            name="ck_pathology_slides_dzi_ready_complete",
        ),
        CheckConstraint(
            "dzi_format IS NULL OR dzi_format IN ('jpeg','png')",
            name="ck_pathology_slides_dzi_format",
        ),
        Index("ix_pathology_slides_patient", "patient_id"),
        Index("ix_pathology_slides_public", "is_public"),
        Index("ix_pathology_slides_tier", "contribution_tier"),
        # Backfill scan: find slides whose pyramid is not yet built.
        Index(
            "ix_pathology_slides_dzi_pending",
            "dzi_ready",
            postgresql_where=text("dzi_ready = FALSE"),
        ),
    )
