"""Post-scrub verification — defense in depth, fails closed.

Re-reads the scrubbed dataset and asserts the de-identification actually held:
no residual private tags, no original-identifier tokens left in any text value,
``PatientIdentityRemoved=YES``. SR / encapsulated-document objects, whose free
text the header engine cannot guarantee clean, are routed to human review
(``RequiresReview``) instead of being served. Any failure raises, and every
egress caller already treats a scrub exception as "withhold this instance", so a
verification miss degrades to no-output, never to a leak.
"""

from __future__ import annotations

import hashlib
import re
import unicodedata

from pydicom.dataset import Dataset

from bvphoenix.services.deid.errors import DeidVerificationError, RequiresReview
from bvphoenix.services.deid.profile_table import ProfileOptions

# Text-ish VRs whose values could still spell out an identifier.
_TEXT_VRS = frozenset({"LO", "SH", "ST", "LT", "UT", "PN", "UC"})
# Original-identifier attributes whose tokens must not survive anywhere.
_PHI_SOURCE_KEYWORDS = (
    "PatientName",
    "PatientID",
    "PatientBirthName",
    "OtherPatientNames",
    "ReferringPhysicianName",
    "AccessionNumber",
)
# >= 2 catches short surnames (Li, Wu, Re). False positives only ever WITHHOLD an
# instance (fail-closed), never leak, so we err broad. Matches the engine's own
# extra-term threshold (engine.py).
_MIN_TOKEN = 2
# The engine's own pseudonym shape (operators.pseudonym). A source value that
# is ALREADY one of our pseudonyms is anonymous by construction — hashing its
# tokens would make every re-scrub (deidentify_reindex after a method-version
# bump re-scrubs at-rest-scrubbed bytes) trip on its own "ANON" sentinel.
_PSEUDONYM_RE = re.compile(r"ANON(-[0-9A-F]{12})?")
# Split on the full punctuation class so "Rossi-Mario" / "Rossi.Mario" tokenise.
_SPLIT_RE = re.compile(r"[\s,^;./\\-]+")


# Engine-generated provenance elements — not patient data, never scanned.
_PROVENANCE_KEYWORDS = frozenset(
    {
        "DeidentificationMethod",
        "DeidentificationMethodCodeSequence",
        "PatientIdentityRemoved",
    }
)


def _norm(token: str) -> str:
    # NFKD + strip diacritics + upper, so "Müller" and "MULLER" hash identically
    # and a downstream ASCII-folded copy can't slip past the comparison.
    return unicodedata.normalize("NFKD", token).encode("ascii", "ignore").decode("ascii").upper()


def _hash(token: str) -> str:
    return hashlib.sha256(_norm(token).encode("utf-8")).hexdigest()


def _tokens(value: object) -> list[str]:
    return [t for t in _SPLIT_RE.split(str(value)) if len(t) >= _MIN_TOKEN]


def collect_phi_hashes(ds: Dataset) -> set[str]:
    """Hash the original high-risk identifier tokens BEFORE scrubbing.

    We keep only salted-free SHA-256 of upper-cased tokens (never plaintext) so
    the verify pass can detect a residual original token without retaining PHI.
    """
    terms: set[str] = set()
    for kw in _PHI_SOURCE_KEYWORDS:
        val = ds.get(kw)
        if val and not _PSEUDONYM_RE.fullmatch(str(val).strip()):
            for token in _tokens(val):
                terms.add(_hash(token.upper()))
    return terms


def assert_clean(ds: Dataset, *, phi_hashes: set[str], options: ProfileOptions) -> None:
    modality = str(ds.get("Modality", "") or "").upper()
    if modality == "SR" or "EncapsulatedDocument" in ds:
        raise RequiresReview(
            "SR / encapsulated document free-text not guaranteed scrubbed by the header engine"
        )
    if str(ds.get("PatientIdentityRemoved", "") or "").upper() != "YES":
        raise DeidVerificationError("PatientIdentityRemoved not set to YES")
    _walk(ds, phi_hashes=phi_hashes, options=options)


def _walk(ds: Dataset, *, phi_hashes: set[str], options: ProfileOptions) -> None:
    for elem in ds:
        tag = elem.tag
        # The engine's own de-identification provenance (the coded
        # DeidentificationMethodCodeSequence text "Retain Patient Characteristics
        # Option" etc.) is generated by us, not patient data — skip it, or a
        # patient whose name shares a word with a CID 7050 meaning would
        # false-positive.
        if elem.keyword in _PROVENANCE_KEYWORDS:
            continue
        if tag.is_private and not options.retain_safe_private:
            raise DeidVerificationError(f"residual private tag {tag}")
        if elem.VR == "SQ" and elem.value is not None:
            for item in elem.value:
                _walk(item, phi_hashes=phi_hashes, options=options)
            continue
        if elem.VR in _TEXT_VRS and elem.value not in (None, ""):
            for token in _tokens(elem.value):
                if _hash(token.upper()) in phi_hashes:
                    raise DeidVerificationError(
                        f"residual PHI token in {tag} ({elem.keyword or 'private'})"
                    )


__all__ = ["assert_clean", "collect_phi_hashes"]
